[package]
name = "PunkVM"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
chrono = "0.4.39"

[dev-dependencies]
rand = "0.9.0"


#[[bin]]
#name = "punkVM"
#path = "src/main.rs"
#
#
#[lib]
#name = "punk_vm"
#path = "src/lib.rs"